### ISSUE TITLE
Wrong FS: daos:/HiBench/Terasort/Input, expected: daos://null

### ISSUE THREAD

**Issue by carsonwang** [zjf2012/daos#11]
Got the following exception if using a path like daos:///HiBench/Terasort/Input. Currently I have to use a path like daos://xxx/HiBench/Terasort/Input.

Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS: daos:/HiBench/Terasort/Input, expected: daos://null

**Comment by zjf2012** [comment]
it's fixed by forcing URI of format daos://ip:port to identify different daos server even though ip and port is not needed to connect to daos server. Just make sure daos://ip:port is unique.

**Comment by carsonwang** [comment]
I think this is just a workaround, instead of a good solution. Can we reopen this?

**Comment by zjf2012** [comment]
ok, maybe there is better solution.

**Comment by zjf2012** [comment]
improved in https://github.com/zjf2012/daos/pull/31
