### ISSUE TITLE
daos_io_server:Received eager message(s) ptype=0x1 opcode=0xd3 from an unknown process (err=49)

### ISSUE THREAD

**Issue by minmingzhu** [zjf2012/daos#14]
restart DAOS cluster after each run, otherwise got the error caused by PSM2 provider.

we cloud not call daos_fini() at the end , so we hit the psm2 issue.

**Comment by zjf2012** [comment]
As confirmed by @minmingzhu , the issue didn't happen recently. We'll see if it happens again in later more test.

**Comment by zjf2012** [comment]
not our issue anymore
