### ISSUE TITLE
We probably shouldn't test on specific implementation details

### ISSUE THREAD

**Issue by gczsjdy** [zjf2012/daos#16]
Like: https://github.com/zjf2012/daos/commit/eb56c5354e2b31ca3becbe305881f989b59e4f51#r36519003
UTs should test on the outcome of a function, but not how the function is implemented.
If we test using the above ways, code refactor may make UTs not passed, which is wrong.

**Comment by zjf2012** [comment]
If DaosFile/DaosFsClient are interfaces, we can create our test implementations of them. Then we examine their internal state outside of functions being tested. There will be no hijiack and mock. I totally agree with your idea.

Unfortunately, they are not interfaces, but concrete classes. There is no better way than mock and verification to do the similar thing as what we do for interfaces. If you look at this mock and verification from angle of interface implementation, they are same.

You can also check test cases shipped by Hadoop test which examines statistics of reading and writing times. It's same intention as mine.
